name: hisa
description: A Dart package to help you to translate an integer to a string in Malagasy language.
version: 0.0.1
repository: https://github.com/rivo2302/dart-hisa
homepage: https://github.com/rivo2302/dart-hisa
issue_tracker: https://github.com/rivo2302/dart-hisa/issues
author_email: rivo2302@gmail.com
license: GPL-3.0

environment:
  sdk: '>=2.19.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
